handle case where instance metadata is not available to serf

diff --git a/images/host/serf/serf-bootstrap b/images/host/serf/serf-bootstrap
--- a/images/host/serf/serf-bootstrap
+++ b/images/host/serf/serf-bootstrap
@@ -2,7 +2,12 @@
 
 id=$(curl -s http://instance-data/latest/meta-data/instance-id)
 region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .region)
-ip=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
+
+if [[ "$id" == "" || "$region" == "" ]]; then
+  echo "Cannot join serf because instance metadata is not available. Exiting in 30s"
+  sleep 30
+  exit 1
+fi
 
 deployment=${TAG_DEPLOYMENT_ID:?"TAG_DEPLOYMENT_ID must be set"}
 environment=${TAG_DEPLOYMENT_ENVIRONMENT}
