handle unavailability of instance metadata

diff --git a/images/host/rancher/rancher-bootstrap b/images/host/rancher/rancher-bootstrap
--- a/images/host/rancher/rancher-bootstrap
+++ b/images/host/rancher/rancher-bootstrap
@@ -31,12 +31,12 @@ if [[ "$uptime" -lt "$GRACE_PERIOD" ]]; then
   exit 1
 fi
 
-self=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
-public=$(curl -s http://instance-data/latest/meta-data/public-ipv4)
-instance_id=$(curl -s http://instance-data/latest/meta-data/instance-id)
-region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .region)
-zone=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .availabilityZone)
-instance_type=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .instanceType)
+self=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+public=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
+instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
+zone=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .availabilityZone)
+instance_type=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .instanceType)
 tags=$(aws ec2 describe-instances --region $region --instance-ids $instance_id | jq -r '.Reservations[0].Instances[0].Tags | map(.Key + "=" + .Value) | reduce .[] as $tag (""; . + $tag + "&")')
 labels="${tags}instance-type=${instance_type}&zone=${zone}&region=${region}&public-ip=${public}&private-ip=${self}&"
 members=($(serf members -format json \
@@ -47,6 +47,12 @@ members=($(serf members -format json \
     | select(.tags.environment == "'$ENVIRONMENT_TAG'")
     | .addr' \
   | awk -F: '{ print $1 }'))
+
+if [[ "$self" == "" || "$public" == "" || "$instance_id" == "" || "$region" == "" || "$zone" == "" || "$instance_type" == "" ]]; then
+  echo "Cannot bootstrap rancher host because instance metadata is not available. Exiting in 30s"
+  sleep 30
+  exit 1
+fi
 
 pong=$(curl -sf --max-time 3 ${RANCHER_SCHEME}://${RANCHER_HOSTNAME}/ping)
 if [[ "$pong" != "pong" ]]; then
diff --git a/images/host/shudder/shudder-bootstrap b/images/host/shudder/shudder-bootstrap
--- a/images/host/shudder/shudder-bootstrap
+++ b/images/host/shudder/shudder-bootstrap
@@ -4,9 +4,15 @@ TAG_DEPLOYMENT_ID=${TAG_DEPLOYMENT_ID:?"TAG_DEPLOYMENT_ID must be set"}
 TERMINATOR_PORT=${TERMINATOR_PORT:-2489}
 cluster_queue_url=${SQS_URL:?"SQS_URL url must be set"}
 
-region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .region)
-my_ip=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
-my_id=$(curl -s http://instance-data/latest/meta-data/instance-id)
+region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
+my_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+my_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+
+if [[ "$region" == "" || "$my_ip" == "" || "$my_id" == "" ]]; then
+  echo "Cannot start shudder because instance metadata is not available. Exiting in 30s"
+  sleep 30
+  exit 1
+fi
 
 cluster_queue_arn=$(aws sqs get-queue-attributes \
   --region $region \
@@ -106,7 +112,7 @@ while true; do
     break
   fi
 
-  terminating=$(curl -sf http://instance-data/latest/meta-data/spot/termination-time)
+  terminating=$(curl -sf http://169.254.169.254/latest/meta-data/spot/termination-time)
   if [[ "$terminating" != "" ]]; then
     echo "Spot instance $my_id is scheduled for termination. Preparing to die." | slack -p -a 'warning'
     break
diff --git a/images/server/backup/backup b/images/server/backup/backup
--- a/images/server/backup/backup
+++ b/images/server/backup/backup
@@ -6,8 +6,8 @@ MYSQL_CONTAINER=${MYSQL_CONTAINER:-mysql}
 ETCD_PORT=${ETCD_PORT:-2379}
 MAX_OLD_SNAPSHOTS=${MIN_OLD_SNAPSHOTS:-3}
 
-my_ip=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
-region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq --raw-output .region)
+my_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
 servers=($(serf members -format json \
   | jq -r '.members
     | sort_by(.tags.up)
@@ -16,6 +16,11 @@ servers=($(serf members -format json \
     | select(.tags.role == "server")
     | .addr' \
   | awk -F: '{ print $1 }'))
+
+if [[ "$my_ip" == "" || "$region" == "" ]]; then
+  echo "Rancher backup failed because instance metadata is not available" | slack -p -a 'danger'
+  exit 1
+fi
 
 if [[ "${servers[1]}" == "" ]]; then
   # I will run the backup if i am the only host
diff --git a/images/server/haproxy/haproxy-conf b/images/server/haproxy/haproxy-conf
--- a/images/server/haproxy/haproxy-conf
+++ b/images/server/haproxy/haproxy-conf
@@ -37,8 +37,14 @@ if [[ "$uptime" -lt "$GRACE_PERIOD" ]]; then
   exit 1
 fi
 
-id=$(curl -s http://instance-data/latest/meta-data/instance-id)
-ip=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
+id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
+
+if [[ "$id" == "" || "$ip" == "" ]]; then
+	echo "Cannot start haproxy-conf because instance metadata is not available. Exiting in 30s"
+	sleep 30
+	exit 1
+fi
 
 if [[ ! -e /etc/haproxy/haproxy.cfg.tmpl ]]; then
 	cp /usr/local/etc/haproxy/haproxy.cfg.tmpl /etc/haproxy/haproxy.cfg.tmpl
diff --git a/images/server/mysql/mysql-backup b/images/server/mysql/mysql-backup
--- a/images/server/mysql/mysql-backup
+++ b/images/server/mysql/mysql-backup
@@ -6,8 +6,14 @@ MYSQL_HOST=${MYSQL_HOST:-localhost}
 MYSQL_VOLUME_NAME=${MYSQL_VOLUME_NAME:-mysqlvol}
 RANCHER_HOSTNAME=${RANCHER_HOSTNAME:?"RANCHER_HOSTNAME must be set"}
 
-REGION=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq --raw-output .region)
-IP=$(curl -s http://instance-data/latest/meta-data/local-ipv4 | tr '.' '-')
+REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
+IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4 | tr '.' '-')
+
+if [[ "$REGION" == "" || "$IP" == "" ]]; then
+  echo "Cannot complete mysql-backup because instance metadata is not available"
+  exit 1
+fi
+
 DESCRIPTION='Rancher mysql database backup'
 VOLUME_ID=$(convoy inspect $MYSQL_VOLUME_NAME | jq -r .DriverInfo.EBSVolumeID)
 
diff --git a/images/server/mysql/mysql-bootstrap b/images/server/mysql/mysql-bootstrap
--- a/images/server/mysql/mysql-bootstrap
+++ b/images/server/mysql/mysql-bootstrap
@@ -35,7 +35,7 @@ chown -R mysql:mysql /var/run/mysqld
 chown -R mysql:mysql /etc/mysql
 chown -R mysql:mysql $MYSQL_DATA_DIR
 
-self=$(curl -s http://instance-data/latest/meta-data/local-ipv4)
+self=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
 ips=($(serf members -format json \
 	| jq -r '.members
 		| sort_by(.tags.up)
@@ -44,6 +44,12 @@ ips=($(serf members -format json \
 		| select(.tags.role == "server")
 		| .addr' \
 	| awk -F: '{ print $1 }'))
+
+if [[ "$self" == "" ]]; then
+	echo "Cannot bootstrap mysql because instance metadata is not available. Exiting in 30s"
+	sleep 30
+	exit 1
+fi
 
 valid=0
 total=0
diff --git a/images/server/mysql/mysql-volume b/images/server/mysql/mysql-volume
--- a/images/server/mysql/mysql-volume
+++ b/images/server/mysql/mysql-volume
@@ -12,8 +12,14 @@ MYSQL_PORT=${MYSQL_PORT:-3306}
 MYSQL_VOLUME_NAME=${MYSQL_VOLUME_NAME:-mysqlvol}
 MYSQL_VOLUME_SIZE=${MYSQL_VOLUME_SIZE:-12G}
 
-REGION=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq --raw-output .region)
-INSTANCE_ID=$(curl -s http://instance-data/latest/meta-data/instance-id)
+REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
+INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+
+if [[ "$REGION" == "" || "$INSTANCE_ID" == "" ]]; then
+  echo "Cannot setup mysql volume because instance metadata is not available. Exiting in 30s"
+  sleep 30
+  exit 1
+fi
 
 alias convoy="system-docker exec convoy convoy"
 
diff --git a/images/server/reporter/reporter b/images/server/reporter/reporter
--- a/images/server/reporter/reporter
+++ b/images/server/reporter/reporter
@@ -4,13 +4,19 @@ CLUSTER_CAPACITY=${CLUSTER_CAPACITY?"CLUSTER_CAPACITY must be set"}
 MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?"MYSQL_ROOT_PASSWORD must be set"}
 RANCHER_HOSTNAME=${RANCHER_HOSTNAME?"RANCHER_HOSTNAME must be set"}
 
-INSTANCE_ID=$(curl -sf http://instance-data/latest/meta-data/instance-id)
+INSTANCE_ID=$(curl -sf http://169.254.169.254/latest/meta-data/instance-id)
 CHECK_INTERVAL=${CHECK_INTERVAL:-10}
 ALERT_COUNT=${ALERT_COUNT:-30}
 FALL_COUNT=${FALL_COUNT:-2}
 RISE_COUNT=${RISE_COUNT:-2}
 MYSQLCHECK_PORT=${MYSQLCHECK_PORT:-2488}
 HAPROXY_MYSQL_PORT=${HAPROXY_MYSQL_PORT:-3307}
+
+if [[ "$INSTANCE_ID" == "" ]]; then
+  echo "Cannot start reporter because instance metadata is not available. Exiting in 30s"
+  sleep 30
+  exit 1
+fi
 
 UNHEALTHY_SIZE=$FALL_COUNT
 UNHEALTHY_MYSQL=$FALL_COUNT
